### ISSUE TITLE
leitura do arquivo

### ISSUE THREAD

**Issue by TulioLima1502** [TulioLima1502/trabalho1#1]
necessita modificar a leitura do arquivo para aceitar o nome sem .asm, pois segundo a especificação do trabalho é assumido que a extensão sempre vai ser essa

**Comment by dfsbora** [comment]
Fiz a função file_exist que recebe o file_name (o argumento da linha de comando), adiciona a extensão '.asm' e verifica se existe no diretório. Retorna 1 se encontrou o arquivo, retorna 0 se não encontrou. 
Coloquei uma chamada a ela no início da main. Se não encontrar arquivo, termina execução
