### ISSUE TITLE
erro léxico com caracteres esquisitos

### ISSUE THREAD

**Issue by TulioLima1502** [TulioLima1502/trabalho1#2]
colocar uma mensagem de erro quando encontrar um caracter não permitido

**Comment by dfsbora** [comment]
Tá dando problema com números. 
solução: testar se o token é o primeiro da linha, se não for, não tem chance de ser rótulo, instriução ou diretiva, então pode ser uma constante e seria válido.

**Comment by dfsbora** [comment]
Fiz foi outra coisa, mas tá funcionando certinho. 
Ideias pra refazer os testes
Tem que dar erros:
LAB:EL:
4VAR

Não pode dar erros
LABEL:
L4BEL:
TAM CONST 54
